### ISSUE TITLE
Email reminders

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Bmore-Responsive#102]
### User Story
As an entity
I'd like to receive email alerts at defined intervals 
So that I can be reminded to check-in with the city.

### Acceptance Criteria
- [x] Functionality to send emails as an alert
- [ ] PR merged to `master`

**Comment by msmith125** [comment]
Hi - I was able to receive an email.  This story mentions sending them at defined intervals.  Has this been coded?  How would we test that?  Thanks!

**Comment by revjtanton** [comment]
By making it an endpoint I'm going to create a trigger mechanism outside of the application itself.
