### ISSUE TITLE
Network COVID Project Update

### ISSUE THREAD

**Issue by bentut** [CodeForBaltimore/Bmore-Responsive#106]
Hello! I’m Ben Trevino and I am a member of the Code for America National Advisory Council. Melanie Mazanec and I are hosting a COVID Response "standup" zoom call (Thursday April 9 @ 8PM EST/5PM PST) to share status updates and needs on active COVID projects in the network. Can someone from this project join the zoom?

Please join us if you are available and/or help us get in contact with project leaders if you know them. Check out slack for details: https://cfa.slack.com/archives/CV1RM8LUB/p1585068294456200

**Comment by revjtanton** [comment]
Yes, I'll be there. Thanks!

--Jason
