### ISSUE TITLE
Many to many entities and contacts

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Bmore-Responsive#121]
### User Story
As an end-user
I'd like to associate many entities to many contacts
So that I can use a product flexible enough to match real-world examples

### Acceptance Criteria
- [x] Sequelize migrations adjuted for new db schema
- [x] Sequelize seeders adjusted
- [x] application models adjusted
- [x] applicable GET, PUSH, and PUT endpoints adjusted for changes in associations
- [ ] Verify that entity/POST enables creation of a new entity with 0, 1, 2 and 10 related contacts
 - [ ] Verify that contact/POST enables creation of a new contact with 0, 1, 2 and 10 related entities
- [ ] Verify that entity/PUT enables ... <<bill to complete>>
- [x] Swagger Docs have been updated

- [ ] PR merged to `master`

### Notes
This may be split into two tasks: the adjustment of migrations/seeders, and then the adjustment to the application.

**Comment by seancrim23** [comment]
linking a contact to entities and vice versa is functional along with performing a GET on a singular Contact/Entity. 
- todo:
- update
- integrate linking in the create endpoints if user wants to link
- lots lots lots of verification

**Comment by c-w-allen** [comment]
We may want to make a new issue to track linking in a create endpoint, since for now we can link using a separate call to `/x/link/{uuid}`
