### ISSUE TITLE
Housekeeping of postman collection

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Bmore-Responsive#136]
### User Story
As a tester on BMore-Responsive
I would like to clean up the postman collection
So that testing is reliable and repeatable.

### Acceptance Criteria
- [x] Use dynamic logic/shared token across collection so it can be used with serve that require login
- [x] Add environment definitions and leverage common baseUrl to make config easier for deployments other than localhost:3000
- [x] Correct error in DEL Entity (currently uses contact end point)
- [x] Add new entity-contact linking endpoints (see Swagger after merge)

**Comment by c-w-allen** [comment]
Added `Add new entity-contact linking endpoints (see Swagger after merge)`
