### ISSUE TITLE
Remove entity phone and email from Swagger doc

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Bmore-Responsive#143]
### User Story
As a developer with Bmore-Responsive
I want the entity phone and entity email removed from Swagger
So that system functionality is documented correctly.

### Acceptance Criteria
- [x] Entity functionality is reviewed thoroughly
- [x] Entity Swagger doc is updated to reflect functionality
- [ ] PR merged to `master`

### Notes
We do currently support in the front end and do not intend to support these attributes.  Swagger doc is misleading.

**Comment by msmith125** [comment]
Verified that phone and email were removed for the create entity and update entity int he swagger doc.
