### ISSUE TITLE
User unable to unlink a contact from entity. 

### ISSUE THREAD

**Issue by sislam17** [CodeForBaltimore/Bmore-Responsive#144]
### User Story
As a Healthcare RollCall user
I want the functionality related to unlinking contacts to work
So that I can unlink contacts

### Acceptance Criteria
- [ ] When on the Facility CheckIn page, I can click on a contact
- [ ] When on the Contact Information page, I can click on `Unlink Contact`
- [ ] When I click on `Unlink Contact` and then `ok` on the pop-up, the contact is unlinked
- [ ] PR merged to `master`
 
### Notes
This was possible via the contact endpoint so it appears to be a front end issue.
curl -X POST "http://localhost:3000/contact/unlink/a8e6d471-e460-4378-9fa4-c22c323671c1" -H "accept: */*" -H "token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1ODA3NTM0MDUsImV4cCI6MTU4MDgzOTgwNX0.Q6W7Vo6By35yjZBeLKkk96s8LyqIE2G39AG1H3LRD9M" -H "Content-Type: application/json" -d "{\"entities\":[{\"id\":\"39fc640e-6342-4aa2-b55f-4a901c923478\"}]}"

While user tries to click on `Unlink Contact` Link, system displays below pop-up. Once user clicks on `ok` from pop-up, API return 404: Not Found. response and Contact is not unlinked.

![image](https://user-images.githubusercontent.com/64163417/81229296-8f0ff500-8fbd-11ea-8300-36f7c66834f0.png)

**Comment by revjtanton** [comment]
This is likely a ticket for the front-end, not the API. I will create the ticket on the front-end.
