### ISSUE TITLE
System unable to load the New Check-In questions when user create an Entity through the API. 

### ISSUE THREAD

**Issue by sislam17** [CodeForBaltimore/Bmore-Responsive#145]
### User Story
As a user of Bmore responsive
I would like for the type column to be populated correctly
so that the check in questions associated with that type are available in the HealthCare UI

### Acceptance Criteria
- [x] Type is populated when an entity is created or updated
- [x] Swagger doc is updated
- [ ] PR merged to `master`

### Notes
While user create an Entity using API, look like type column is not updated in the entity table. 

![image](https://user-images.githubusercontent.com/64163417/81229586-1198b480-8fbe-11ea-8462-b1d8a4a840e7.png)

**Comment by msmith125** [comment]
I created an Entity as Assisted Living Facility and the check in questions where there.  When I tried to update the Entity to a different type, it worked and the type showed up in the db and the questions were gone as expected.  When I changed the type back to Assisted Living Facility, the check-in questions no longer loaded.  I think this still might have some minor issues.
