### ISSUE TITLE
Require non-empty names for Facilities and Contacts

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Bmore-Responsive#156]
### User Story
As a User of the Bmore-Responsive system
I'd like to require that Facilities and Contacts have names that are not blank
So that I can ensure that blank names do not show on the Facility Dashboard and Contact List in the HealthCare RollCall UI

### Acceptance Criteria
- [x] "" is not allowed as a Facility Name when creating or updating Facilities
- [x] "" is not allowed as a Contact Name when creating or updating Contacts
- [x] Swagger Doc is updated to reflect that these fields require data
- [ ] PR merged to `master`

### Notes
Currently these fields can be blank which do show up in the HealthCare RollCall UI

**Comment by revjtanton** [comment]
You have to go to _Schema_ in swagger to see it's required.

**Comment by msmith125** [comment]
When creating a facility or contact, this is working.  However, you can still update a facility or contact to have an empty name.  So, the create seems fine but the update is allowing empty names.
