### ISSUE TITLE
UserRole Export to CSV is not returning results

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Bmore-Responsive#158]
### User Story
As a developer on the Bmore-responsive project
I'd like to be able to export UserRoles to csv
So that I can see which UserRoles are available to create/update users with

### Acceptance Criteria
- [x] Remove UserRoles and User exports
- [x] Swagger doc is updated
- [x] Postman collection is updated if required
- [ ] PR merged to `master`

### Notes
When you try to export UserRole to CSV, no results are returned.  Here is the messaging from the local window running bmore-responsive:

Executing (default): SELECT "id", "ptype", "v0", "v1", "v2", "v3", "v4", "v5", "createdAt", "updatedAt" FROM "public"."casbin_rules" AS "casbin_rule";
::1 - - [20/May/2020:11:47:56 +0000] "GET /csv/UserRole HTTP/1.1" 200 -

**Comment by revjtanton** [comment]
I am removing User and UserRole options from the CSV endpoint. These should not be exported in this way.

**Comment by msmith125** [comment]
Validated that swagger doc and Postman no longer contain options for User and UserRole.  This looks good.
