### ISSUE TITLE
Entity export to CSV is failing

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Bmore-Responsive#159]
### User Story
As a developer on the Bmore-responsive project
I'd like to be able to export Entities to csv
So that I can see which Entities are present in the db

### Acceptance Criteria
- [ ] Export of Entity exports results
- [ ] Swagger doc is updated
- [ ] Postman collection is updated if required
- [ ] PR merged to `master`

### Notes
When you try to export Entity to CSV, no results are returned and a "500" error is received.  Here is the messaging from the local window running bmore-responsive:

![image](https://user-images.githubusercontent.com/58228205/82443499-9c25ed00-9a6f-11ea-82f1-becb3503dc84.png)

**Comment by revjtanton** [comment]
I am not able to replicate this issue @msmith125

**Comment by msmith125** [comment]
I could not recreate with PR 180.  Perhaps it was specific to my data at the time or the build I was working with.  Closing.
