### ISSUE TITLE
Cannot remove a role with the latest master build

### ISSUE THREAD

**Issue by msmith125** [CodeForBaltimore/Bmore-Responsive#172]
**Describe the bug**
When trying to remove a role, Invalid Input Error is returned

**To Reproduce**
1. Use post command (.../userRole/delete) to try to delete an existing UserRole
curl --location --request POST 'http://localhost:3000/userRole/delete' \
--header 'token: "ENTER TOKEN \
--header 'Content-Type: text/plain' \
--data-raw '{
  "role": "test2",
  "path": "/test",
  "method": "GET"
}'

**Expected behavior**
When attempting to delete a UserRole, as long as command is formatted correctly and the role exists, it should delete.

**Environment**
Latest master build with simpson data seeded

**Additional context**
This is a new problem that started on 5/22.

**Comment by revjtanton** [comment]
I am not able to recreate this error @msmith125

**Comment by msmith125** [comment]
I was also not able to recreate with swagger with PR 181.
