### ISSUE TITLE
Improve data seeder to use realistic factility types

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Bmore-Responsive#241]
### Task
npm run db-seed currently makes all facilities "test" facilities, it is more useful to have the db seeded with "Assisted Living" and "Senior Housing" types.

**Comment by revjtanton** [comment]
This is going to be part of the type endpoint being addressed in another ticket. We need less hardcoded types in the first place, so there should be seeding of entity types and _that_ would allow the facility to be valid in example seeding.

**Comment by blakenan-bellese** [comment]
OK.  I'll keep my edits locally then and close this issue.
