### ISSUE TITLE
terraform 

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Bmore-Responsive#25]
### User Story
As a developer
I'd like to deploy our Docker solutions to Heroku or AWS through terraform
So that I can manage infrastructure as code

### Acceptance Criteria
- [x] Docker container pushing to CfB dockerhub repo
- [x] terraform scripts created to setup Heroku _or_ AWS environment
- [ ] auto deploy of new code to dev environment either via Travis or terraform
- [ ] PR merged to `master` with above changes

### Notes
Dependant on #12

**Comment by jbixon13** [comment]
What are the benefits to deploying to heroku with terraform instead of travis?

**Comment by revjtanton** [comment]
> What are the benefits to deploying to heroku with terraform instead of travis?

We wouldn't be deploying with Terraform, we'd still be deploying with Travis. Terraform would provision our infrastructure and manage that. So it would set up Postgres, configure the pipeline, etc, so all that would otherwise be done in a GUI would be managed in code. This will allow others to easily deploy their own implementation of our solution. 

Also, because we're going to be deploying a Dockerized solution, we could also throw in AWS or Azure solutions with Terraform that work just as out-of-the-box as our Heroku solution will. Terraform will let us one-button deploy the entire solution end to end, and then Travis would manage monitoring of either our Github or Docker repos (probably Github for dev and Docker for impl and prod) for deployment.
