### ISSUE TITLE
Update wiki with --build option on Quick Start page

### ISSUE THREAD

**Issue by kabera-bellese** [CodeForBaltimore/Bmore-Responsive#326]
### Task
Update the command on step 4 in the [quick start page](https://codeforbaltimore.github.io/Bmore-Responsive/QuickStart/) to include --build option.

### Acceptance Criteria
- Update step 4's command from `docker-compose up -d` to `docker-compose up -d --build`

**Comment by hidekysilva** [comment]
I would like to submit a PR for this issue. How do I get permission to create a branch for my PR?

**Comment by kabera-bellese** [comment]
Hi, please refer to[file](https://github.com/CodeForBaltimore/Bmore-Responsive/blob/master/CONTRIBUTING.md) for some contribution guides.

Steps:
1 - Fork the project
2 - Download project on your local
3 - Create a branch off of master. Naming convention for branches should be <your github username>/issue-<github issue number>
4 - Commit and push your branch to your forked project.
5 - Create PR using the template defined for the project.

cc: @blakenan-bellese

**Comment by hidekysilva** [comment]
Thanks. Here's the PR https://github.com/CodeForBaltimore/Bmore-Responsive/pull/329

**Comment by blakenan-bellese** [comment]
@hidekysilva Thanks for your contribution.  Your PR has been approved, merged and deployed.  You can see the impact here: https://codeforbaltimore.github.io/Bmore-Responsive/QuickStart/
