### ISSUE TITLE
Swagger and possible code defect in POST ~/user - example gives 400

### ISSUE THREAD

**Issue by carorm** [CodeForBaltimore/Bmore-Responsive#343]
**Describe the bug**
Swagger provides the following:
```
{
  "relationshipTitle": [
    "Primary Contact"
  ],
  "contactIds": [
    "ba262fa3-38d9-4c88-b49b-ab306349124a"
  ],
  "entityIds": [
    "ba262fa3-38d9-4c88-b49b-ab306349124a"
  ],
  "entityType": "Assisted Living Facility"
}
```

And it still does 400 - Bad Request.

**To Reproduce**
1. Download bmore project
2. Run it locally via docker
3. Run POST {{baseUrl}}/contact/send locally with a payload from swagger example
4. See that it populates with a 400.

**Expected behavior**
User should be created based off swagger information or update the swagger to show what it should be instead. Postman collection was missing just about every field it looks like as well so that wasn't the issue either. Once the swagger is updated, can make adjustments to postman as well.

**Environment**
A concise description of your environment:  Catalina 10.15.7. Docker version 20.10.0, build 7287ab3. NPM = 7.0.10. Ran from master branch on 12/31/2020 @ 3:00PM EST.

**Additional context**

**Comment by blakenan-bellese** [comment]
I think this might be more than a documentation defect.  The following input also produced a 400 error: 

{
  "email": "swans.ron@meparks.com",
  "password": "superRocks!",
  "roles": 
    [
    "user"
    ],
  "displayName": "Swans Ron",
  "phone": "1234567890"
}

**Comment by c-malecki** [comment]
I'm not sure if I'm misunderstanding the issue but what I did notice is that the server URL specified in `swagger.json` is for `localhost:3000` and not `localhost:3001`. `3001` is the port the server/API is actually running on, right? And `3000` is where the client-side is usually served.

Changing it to 3001 receives a status 200 response in Swagger, but no response seems to be printed in the GUI.

![image](https://user-images.githubusercontent.com/50671267/105422459-c983f580-5c11-11eb-9ecb-3a2562378a2c.png)

When making the same requests via Postman, I do see and receive the proper response bodies.

**Comment by c-malecki** [comment]
As an additional note per this specific endpoint, using Bill's request body above returns what I'm guessing is a correct response:
```
{"results":{"message":"Contacts emailed","totalContacts":25,"totalEntities":25}}
```
 The default request body provided by Swagger returns "No contacts to email," which upon opening in a new tab says: "Invalid UUID" - so I think that's just a documentation error where the provided request body's IDs don't exist in the DB entities generated with Sequalize.

**Comment by jameswgoddard** [comment]
For POST /user the error messages should be more specific. I'll submit a pull request tomorrow. The examples above violate the password complexity requirements and / or are duplicate Emails. 

The following returns a 200 status code:
{
"email": "swans.ron@meparks.com",
"password": "superRocks!1",
"roles":
[
"user"
],
"displayName": "Swans Ron",
"phone": "1234567890"
}

**Comment by blakenan-bellese** [comment]
Jim,
                Sounds good, thanks.  A coupe favors…  Can you assign yourself to the issue and can you update the swagger JSON, as needed to reflect your updates?  Thanks


[signature_707769356]

Bill Lakenan
Bellese Technologies | bellese.io
blakenan@bellese.io<mailto:blakenan@bellese.io>  |  443-914-2126
300 Red Brook Blvd, Owings Mills, MD 21117
[https://lh3.googleusercontent.com/-l-MSfbYFAnCvqklJE30UrLFPpNrtvIWKu3Y-7b8YfHhjFo5eLZjcMtoctL7cl6EWWc1MBBdxdfmf0w2fXGodEWk01bd6RtrvBC1LqjAYbvItinODkiEPVjeIYKSHJap3qwIxjsM]<https://www.linkedin.com/company/2705760/> [https://lh4.googleusercontent.com/QNJbiLeSHzDK4DPi0QCoSi7jcoWfVnDUMUPCVXm86rk_4iRu8RasvhalLLiXNE7EqHEp8ARRWItZQ8PSIB4Np7HFC520sEBYwbUCE4as5ykVcog22WWDeJQesZDEAd14u3MubYPs] <https://www.facebook.com/Bellese-Technologies-490279364472269>
