### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SavSanta** [CodeForBaltimore/Bmore-Responsive#63]
api_1  | [nodemon] 2.0.2
api_1  | [nodemon] to restart at any time, enter `rs`
api_1  | [nodemon] watching dir(s): *.*
api_1  | [nodemon] watching extensions: js,mjs,json
api_1  | [nodemon] starting `babel-node src/index.js`
api_1  | Executing (default): SELECT 1+1 AS result
api_1  | Executing (default): CREATE TABLE IF NOT EXISTS "public"."Contacts" ("id" UUID UNIQUE , "UserId" VARCHAR(255) REFERENCES "public"."User" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "name" VARCHAR(255), "phone" JSON, "email" JSON, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
api_1  | Connection to database successful
*db_1   | 2020-03-21 08:40:07.024 UTC [32] ERROR:  relation "public.User" does not exist*
db_1   | 2020-03-21 08:40:07.024 UTC [32] STATEMENT:  CREATE TABLE IF NOT EXISTS "public"."Contacts" ("id" UUID UNIQUE , "UserId" VARCHAR(255) REFERENCES "public"."User" ("id") ON DELETE NO ACTION ON UPDATE CASCADE, "name" VARCHAR(255), "phone" JSON, "email" JSON, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
api_1  | Unhandled rejection SequelizeDatabaseError: relation "public.User" does not exist
api_1  |     at Query.formatError (/usr/src/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
api_1  |     at /usr/src/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
api_1  |     at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
api_1  |     at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
api_1  |     at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
api_1  |     at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
api_1  |     at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:725:18)
api_1  |     at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
api_1  |     at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
api_1  |     at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
api_1  |     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
api_1  |     at processImmediate (internal/timers.js:439:21)
api_1  |     at process.topLevelDomainCallback (domain.js:131:23)
api_1  | [nodemon] clean exit - waiting for changes before restart

While trying to run with `docker-compose up`. I get the following error. Anything I'm missing on doing. Not a nodejs fellow

**Comment by revjtanton** [comment]
Looking into it.
