### ISSUE TITLE
Export to CSV (w/o roles, w/o questions)

### ISSUE THREAD

**Issue by revjtanton** [CodeForBaltimore/Bmore-Responsive#99]
### User Story
As an city employee
I'd like to understand the status of all facilities' check-ins
So that I can use the data for other purposes.

### Acceptance Criteria
- [x] Export endpoints created
- [x] Includes 1 row per facility with latest check-in status per facility on total dashboard page(s)
- [x] Swagger doc updated
- [x] no need to include question responses
- [x] Export based on query string (_optional_)
- [x] PR merged to `master`

### Notes
Should correspond to filters set on front-end. Params sent via query string or better solution.

**Comment by revjtanton** [comment]
Let's see if we can treat this as a CSV "view" of a `GET` endpoint? So if we go to `/entities` we get a json response but if we go to `/csv/entities` we get more or less the same response, but in CSV format?

That might be a future thing.

**Comment by seancrim23** [comment]
added functionality for "/csv/{model_type}". whatever model type you pass in, be it Entity/User/etc, will return a csv dump of all of the data for that particular model

**Comment by seancrim23** [comment]
results are now processed depending on their type. for example, if Entity results are processed, the most recent check in is returned rather than every check in. the processing function is set up so further logic can be added for each type that we want custom processing on
